### ISSUE TITLE
Change modules layout in the project

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#442]
Hide all the projects of `service-gateway-x`  and `services-transport` folders under one folder named `scalecube-gateway` folder and `services-transport` folder

so in `scalecube-services` repo we will have top level projects of:
_services_
_services-api_
_services-discovery_
_services-transport_

**Comment by snripa** [comment]
@artem-v did u think of removing ''services '' from the names also(since we are already  in services parent proj)? in this case - 'services'' -> "core"

**Comment by segabriel** [comment]
@snripa I think we need just to move all gateway in `services-gateway` directory, but leave their artifactIds as are

**Comment by ronenhamias** [comment]
usually the project name should reflect the artifact name.
so having just `api` or core means nothing.

IMHO gateway should be in sperated repository but if not at least in seperated module.

**Comment by ronenhamias** [comment]
gateway is now removed to its own repository
