### ISSUE TITLE
Explore micrometer.io

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#448]
https://www.nurkiewicz.com/2018/01/spring-boot-2-migrating-from-dropwizard

https://vertx.io/blog/eclipse-vert-x-metrics-now-with-micrometer-io/

https://ordina-jworks.github.io/microservices/2017/09/17/monitoring-your-microservices-with-micrometer.html

**Comment by snripa** [comment]
1st link is broken https://dzone.com/articles/spring-boot-2-migrating-from-dropwizard-to-micrometer
