### ISSUE TITLE
Move API project to another repository (different CI)

### ISSUE THREAD

**Issue by aharonha** [scalecube/scalecube-services#475]
The main API of scalecube should be separated from this project in order to use it in independent projects, without requiring the actual release version updated:

I have a utility project which it's dependency in scalecube is only by API. I want to avoid dictating the dependencies of scalecube-services on my dependants. whoever uses my project should be depended on whatever version of scalecube implementation thus avoiding dependency collisions.

Please include a new interface for `Microservices` (`shutdown()` and `call()` are required now)

**Comment by ronenhamias** [comment]
i think the requirement is not to have dependencies in api module and not to move it elsewhere...

**Comment by ronenhamias** [comment]
project structure already changed.
closing as done
