### ISSUE TITLE
investigate if switchOnFirst may replace HeadAndTail.

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube-services#509]
![image](https://user-images.githubusercontent.com/1706296/51676282-d481fc00-1fde-11e9-9044-0392dae7235b.png)

https://github.com/scalecube/scalecube-services/blob/a9761776973df8d990658eeffca7d5025f58b209/services/src/main/java/io/scalecube/services/ServiceCall.java#L204

https://github.com/reactor/reactor-core/pull/1423/files#diff-c590f0f2fbe1d419bdccc521a1894278R186

https://github.com/reactor/reactor-core/pull/1423/files#diff-1496e2df144760bd5a12dbd0c149f40eR148

**Comment by artem-v** [comment]
Fixed at https://github.com/scalecube/scalecube-services/pull/510
