### ISSUE TITLE
Change behavior handling of consumer/supplier in builder

### ISSUE THREAD

**Issue by segabriel** [scalecube/scalecube-services#512]
for now, I lose the previous settings when I invoke the options setter several times:

```
      Microservices.builder()
            .discovery(options -> options.seeds(seed.discovery().address()))
            .discovery(options -> options.port(123))
            .discovery(options -> options.memberHost("member"))
``` 

I'd like to propose making it in the `Microservices` like this: 
```java
public Builder discovery(Consumer<ServiceDiscoveryConfig.Builder> discoveryOptions) {
     if (this.discoveryOptions != null) {
      this.discoveryOptions = this.discoveryOptions.andThen(discoveryOptions);
    } else {
      this.discoveryOptions = discoveryOptions;
    }
...
```

**Comment by ronenhamias** [comment]
this is very verbose can you explain the value and what it try to solve?

**Comment by segabriel** [comment]
@ronenhamias currently, we just override options when we invoke them again. For example, if I set some seed address firstly and then I want to add members and to do it I need to specify the seed again and the members.

**Comment by segabriel** [comment]
And java `Consumer` and `Supplier` allow do it with `andThen` or `thenApply`

**Comment by ronenhamias** [comment]
can you provide an example that demonstrate a problem or uscase that have issue and how it can be solved?

**Comment by segabriel** [comment]
@ronenhamias What do you expect from the next sample? 

```java
Microservices.builder()
            .discovery(options -> options.host("177.17.0.1"))
            .discovery(options -> options.port(8888))
```

The current behavior will try to connect to **localhost**:8888 instead of **177.17.0.1**:8888.

**Comment by artem-v** [comment]
@segabriel 

As you know I worked to fix  this behavior just recently. Go ahead and verify you concerns with latest code.

**Comment by segabriel** [comment]
@artem-v 
I have revised it after your changes, and your changes fixed the mentioned problem (we always create a new `ScalecubeServiceDiscovery` instance and apply previous and new options).
