### ISSUE TITLE
Class ServiceCall.Call must be immutable

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#523]
Subj. 
Class `Call` is mutable. Make it immutable.

**Comment by ronenhamias** [comment]
Class `ServiceCall.Call` is actually a builder

`mandatory fields` are passed in the ctor.
```java
public Call(
        ClientTransport transport,
        ServiceMethodRegistry methodRegistry,
        ServiceRegistry serviceRegistry) {
      this.transport = transport;
      this.serviceRegistry = serviceRegistry;
      this.methodRegistry = methodRegistry;
    }
```

`the optionals` is set in a builder fluent way.

```java
public Call router(Class<? extends Router> routerType) {
      this.router = Routers.getRouter(routerType);
      return this;
    }

    public Call router(Router router) {
      this.router = router;
      return this;
    }

    public Call errorMapper(ServiceClientErrorMapper errorMapper) {
      this.errorMapper = errorMapper;
      return this;
    }
```

and then the `build` phase is the create method:

```java
public ServiceCall create() {
      return new ServiceCall(this);
    }
```

**Comment by artem-v** [comment]
Exactly, mutable builder. And this is a problem.

`Call` object is shared in several  places:  in service provider, when defining gateway

**Comment by ronenhamias** [comment]
call is a builder why its shared in several places?
it is used to build a ServiceCall
is there more places we share builders?

**Comment by artem-v** [comment]
> call is a builder why its shared in several places?

Because
1 service provider might want to set custom settings, like custom router
2 same applies when defining gateway
