### ISSUE TITLE
Block Microservices on termination signal

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#529]
After microservices has started block it on termination signal (such as SIGTERM for example).
Upon receiving exiting signal do microservices shutdown.

http://man7.org/linux/man-pages/man7/signal.7.html
https://docs.oracle.com/javase/10/troubleshoot/handle-signals-and-exceptions.htm#JSTGD345

**Comment by artem-v** [comment]
https://unix.stackexchange.com/questions/317492/list-of-kill-signals

**Comment by segabriel** [comment]
Let's investigate that implementation https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/SigInt.java#L30

**Comment by artem-v** [comment]
See also 
https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/j9_signals_j9_handling.html

**Comment by artem-v** [comment]
See also 
https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html

**Comment by artem-v** [comment]
See also 
https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/j9_signals_j9_handling.html

**Comment by artem-v** [comment]
Little contract for  `Mono<Void> onJvmShutdown()` (further referred as OJS) here:

1. if Microservices instance has already been shut down or  is in process of shutdown then:
  1.1. calling OJS must not start to listen termination signals, but just wait until `dispose()`  mechanism finishes its job.

2. if Microservices was successfully launched and later on OS terminated JVM, then OJS must be called. 
  2.1. At this point `Microservices.dispose()`  must be called -- if **it fails**, never mind, log this occurrence; if it succeeded -- do nothing.
