### ISSUE TITLE
Add running/idle flag

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#530]
ServiceDiscovery must have a state, state update and state query functions.
States: Running, Idle or null (which must be treated as New).
Query: isNew(), isIdle() and isRunning().
Update operations: setIdle(), setRunning().

**Comment by ronenhamias** [comment]
what is the propose of this flags?

**Comment by artem-v** [comment]
This flag will tell is node ready  to accept  requests. Main idea (about which i forgot to mention in description)  make this state property   accountable when Router  selects nodes.
