### ISSUE TITLE
explosion of Address classes

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube-services#565]
in scalecube we have explosion of Address classes. 

consolidate Address class to just one class and use  in relevant scalecube projects.

**Comment by artem-v** [comment]
Every  project  may define  their own  Addres class,  what is  wrong  with  this.

**Comment by ronenhamias** [comment]
its mostly duplication of code everywhere and conversions

**Comment by ronenhamias** [comment]
done
