### ISSUE TITLE
Consolidate Client SDK wiith ServiceCall

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube-services#578]
Motivation: today client sdk is mainly used as client for ApiGateway. and ServiceCall is used for internal communication inside the cluster

an alternative would be to allow ServiceCall communicate as client via GW transport with service.

that means that service call can be bootstrap without discovery and router and with GW transport so it directly communicating and invoking services via the GW

as result Client SDK is just GW transport providers for service call.

**Comment by snripa** [comment]
lets clarify a few poins here:

1. currently client sdk supports 'requestOne' and requestStream only. Should we support als bidirectional communication and fireNForget?
2. Whether all 3 implementations needed in scope of this issue: websocket/rsocket/http

**Comment by ronenhamias** [comment]
1. yes
2. yes - in http we can throw unsupported operation in case of not request response.

**Comment by artem-v** [comment]
Implemented (and verified later) on https://github.com/scalecube/scalecube-gateway/commit/893c40b497660799f17d034831b4fc33c372f9d2.  Thank you @snripa.
