### ISSUE TITLE
Random test

### ISSUE THREAD

**Issue by segabriel** [scalecube/scalecube-services#612]
Subj: 

- [ ] `ScalecubeServiceDiscoveryTest.lambda$testGroupEventsOnBehalfOfNonGroupMember$42:270 expected: <ENDPOINT_REMOVED_FROM_GROUP> but was: <ENDPOINT_ADDED_TO_GROUP>`

- [ ] `ScalecubeServiceDiscoveryTest.testSingleNodeGroupIsStillGroup:222 VerifySubscriber timed out on reactor.core.publisher.FluxFlatMap$FlatMapMain@4037fcc`

**Comment by artem-v** [comment]
Those tests have been fixed in recent releases. Closing.
