### ISSUE TITLE
Add support of polymorphic types

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#638]
Subj.

Consider to write header `_type` conditionally to the response message. For example it's possible to deduct that class in return type (or in `@Response`  annotation)  is abstract or interface and store this polymorphic indicator  (e.g. `boolean morph`  flag)   in the `MethodInfo`.

**Comment by segabriel** [comment]
IMHO we should delete this header (`_type`) at all.

**Comment by eutkin** [comment]
Could it allow a user to add custom codecs (which would take precedence over the default codec) for some complex cases?

**Comment by eutkin** [comment]
I learned that we can only have one argument in the service interfaces. What if we wrap all interface arguments in an array and pass an array of types or other information to decode?

**Comment by artem-v** [comment]
@eutkin 
see comment https://github.com/scalecube/scalecube-services/issues/639#issuecomment-512804187

**Comment by artem-v** [comment]
It's agreed it can be solved on encoder/decoder level. Closing.
