### ISSUE TITLE
Checks @Principal annotation in not-auth method

### ISSUE THREAD

**Issue by eutkin** [scalecube/scalecube-services#639]
I have interface: 

```java
@Service("destination-selector")
public interface DestinationSelector {

    @ServiceMethod("select")
    Mono<Destination> select(SelectContext selectContext, List<Destination> source);

}
```

My app down this exception: `The second parameter can be only @Principal (optional)`.
I not want use security in this app. 

Correctly this behavior in scalecube services?

**Comment by dmytro-lazebnyi** [comment]
`scalecube-services` doesn't support 2 input parameters for `@ServiceMethod` (since `ServiceMessage` contains only one `data`).
The second parameter allowed only if it is annotated with `@Principal` (for `@Auth` methods).

**Comment by eutkin** [comment]
Doesn't anybody think that there's only one argument to have a serious limitation?

**Comment by segabriel** [comment]
@eutkin How do you propose to resolve it? So we receive a body from a request, how to split it up?  Currently we support only one body and the auth stuff (if it was marked with the annotation).
We can add an annotation like `@RequestBody` to don't rely on the order.

**Comment by eutkin** [comment]
@segabriel https://github.com/scalecube/scalecube-services/issues/638#issuecomment-512789203

**Comment by artem-v** [comment]
Wrap parameters `SelectContext selectContext, List<Destination> source` into single request class  `DestinationSelectorRequest`.

**Comment by eutkin** [comment]
@artem-v maybe wrap this parameters in ServiceMessage? The first thing that comes to mind, instead of `T data` and `_type`, is to pass `Object[] data`, `Class[] _types` inside `ServiceMessage`. In my opinion it makes the API more user-friendly. Besides, I don't see any technical limitations here that would prevent us from doing something like **transfer multiple parameters**.
