### ISSUE TITLE
Is there a way to remove the node from the scalecube cluster/network after sometime or incase of indifferent behavior.

### ISSUE THREAD

**Issue by riya-goyal** [scalecube/scalecube-services#658]
I have a 5-node cluster which is working fine for the first 2 hours ( let's say) . 
After that I am seeing an issue where 2 of the nodes are not able to gossip properly or receiving the messages properly.
I want to remove them at this stage once I know that they are corrupted . Can we do this through code implicitly. 
And also can we figure it out internally that the node is corrupted and it should be removed from the scalecube cluster.

**Comment by artem-v** [comment]
@riya-goyal 
put more details. logs, errors, version of the cluster library, its configuration, describe environment.
