### ISSUE TITLE
Zero dependencies codec

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#724]
Goals: allow to use microservices transport with codec which has zero dependencies on 3rdpaties (no jackson no proto). 

Subtasks:
* Create `JdkCodec` (take a look at `io.scalecube.cluster.transport.api.JdkMessageCodec` and `io.scalecube.cluster.metadata.JdkMetadataCodec` are done in `scalecube-cluster` project). 
* Create test where u send data-format of type `application/octet-stream`.
* Rename `DefaultHeadersCodec` to `JdkHeadersCodec`. **Hint: reuse this codec (aggregation) when  u will develop `JdkCodec`.

**Comment by eutkin** [comment]
@artem-v 
Is netty buffer considered a 3d party? Need to create a separate module or add jdk codec to services-bytebuf-codec?

**Comment by artem-v** [comment]
> @artem-v
> Is netty buffer considered a 3d party? Need to create a separate module or add jdk codec to services-bytebuf-codec?

IMHO let's leave netty where it's now. jdk codec must go to place as I put in [this comment](https://github.com/scalecube/scalecube-services/pull/726#pullrequestreview-407298600).
