### ISSUE TITLE
Remove @Principal

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#729]
Subj.

Remove special second paramter `@Principal` (maybe `@Auth` as well!). 
**Use Mono/Flux  with deffered context to propagate security context.**
Create deffered context when on receiving sides  1/ gateways   2/ service server transport. There has to be 2 types of contexts : 1/ session context   2/   request context.  **For HTTP a  session context and request context are the same.

**Comment by aharonha** [comment]
Can you please elaborate on the flow?
As I know, the main mechanism is using the `@Principal` to pass the context to the service itself.
How would the new mechanism perform this?

**Comment by artem-v** [comment]
@aharonha 
it's all about reactor's feature (undeservedly forgotten)  called  `deferWithContext`. It's a method defined on `Mono` or `Flux`. 

For example like this one (code chunk from websocket gw): 

```java
    session
        .receive()
        .subscribe(
            byteBuf ->
                Mono.deferWithContext(context -> letsGo(session, byteBuf, context))
                    .subscriberContext(
                        context -> createContext(session, byteBuf, context))
                    .subscribe());
```

And somewhere down the road of `letsGo`  there will be this one (code chunk from exchange code): 

```java
  @Override
  public <T> Mono<T> requestResponse(long correlationId, Object request) {
    return Mono.deferWithContext(
        context -> {
          Encoder encoder = requestEncoder.get();
          DirectBuffer buffer = encoder.encode(request, correlationId);
         ...
```

So basically u can propagate some reactor context till the edge. Hence, in a context of exaclty this ticket, this edge would be  service method, i.e reactor context could be propagated up to service method, hence we don't need principal in parameters, we can pass it through reactor context.

**Comment by aharonha** [comment]
@artem-v Do you mean that instead of having a parameter of `@Principal`, and another parameter of request, the interface would have single parameter of `Mono<Request Type>` in which the context contains the principal?

**Comment by artem-v** [comment]
> @artem-v Do you mean that instead of having a parameter of `@Principal`, and another parameter of request, the interface would have single parameter of `Mono<Request Type>` in which the context contains the principal?

> Do you mean that instead of having a parameter of @Principal, and another parameter of request

Nope. Leave service method as it supposed to be from very beginning -- clean service method with single parameter. I will create PR to start really on upon this feature.
