### ISSUE TITLE
Reconsider/refactor/simplify code in .toResponse

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#746]
Subj.

IMHO could be simplified.

```
  private ServiceMessage toResponse(Object response, String dataFormat) {
    if (response instanceof ServiceMessage) {
      ServiceMessage message = (ServiceMessage) response;
      if (dataFormat != null && !dataFormat.equals(message.dataFormat())) {
        return ServiceMessage.from(message).dataFormat(dataFormat).build();
      }
      return message;
    }
    return ServiceMessage.builder()
        .qualifier(methodInfo.qualifier())
        .data(response)
        .dataFormatIfAbsent(dataFormat)
        .build();
  }
```

**Comment by ronenhamias** [comment]
can we include `String dataFormat` in message header?
this data format on method signature is kind of not nice.

data format can be the outcome of codec that used to parse this message

**Comment by artem-v** [comment]
> can we include `String dataFormat` in message header?

It's already inside message header. It's not part of method signature.

**Comment by ronenhamias** [comment]
yes but `ServiceMethodInvoker` should always have same data format meaning no need to pass this variable

if you passed via `ServiceMethodInvoker` it encode and decode in same way.

meaning that we should have `ServiceMethodInvoker` per codec
