### ISSUE TITLE
Change error qualifer format

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#751]
Migrate `io.scalecube.services.error/:errorType`  to  message with normal qualifier  but with header denoting error type. Leave ErrorData as is.

Add `_error_type`  header (name it by analog with `_data_format`).

Remove method `Qualfier.isError`, change inplementation of `ServiceMessage.isError`.

**Comment by dudikrisher** [comment]
@segabriel @artem-v 
Why field name is `_error_type` and not `errorType` ?

**Comment by artem-v** [comment]
> @segabriel @artem-v
> Why field name is `_error_type` and not `errorType` ?

To be consistent with current naming conventions: 

```
  public static final String HEADER_DATA_TYPE = "_type";

  public static final String HEADER_DATA_FORMAT = "_data_format";

```

**Comment by dudikrisher** [comment]
But `_type` is never exposed to public and this one exposed so it should use convention of all the other fields in message

**Comment by dudikrisher** [comment]
lets fixed it here: https://github.com/scalecube/scalecube-services/issues/757
