### ISSUE TITLE
NoSuchElementException from Microservices#discovery  

### ISSUE THREAD

**Issue by segabriel** [scalecube/scalecube-services#771]
See io.scalecube.services.Microservices#discovery

```
public ServiceDiscoveryContext discovery(String id) {
  return Optional.ofNullable(compositeDiscovery.contextMap.get(id))
      .orElseThrow(() -> new NoSuchElementException("[discovery] id: " + id));
}
```

![image (1)](https://user-images.githubusercontent.com/12995984/85023952-0d93b100-b17e-11ea-9556-c287d810e9ce.png)

**Comment by artem-v** [comment]
This is where? Under what circkumstances?

**Comment by segabriel** [comment]
@artem-v `io.scalecube.services.Microservices#discovery`

**Comment by segabriel** [comment]
I just put it like

```
Microservices.builder()

              .discovery("private", privateDiscoveryFactory)
```

**Comment by artem-v** [comment]
Fixed at https://github.com/scalecube/scalecube-services/pull/772
