### ISSUE TITLE
Is there any up to date documentation anywhere?

### ISSUE THREAD

**Issue by cyberpwnn** [scalecube/scalecube-services#797]
It looks like a lot of the examples and quickstarts were for older versions? For example `.discovery(o -> o.seeds(seed.discovery().address()))` is explained nowhere, and I'm not sure what it does. It's also been changed to require a String (id) and transport factory. 

I'm also having a lot of trouble figuring out what dependencies are needed because the ones listed arent even artifacts, and the ones specified that do exist are not all of what i need?

**Comment by ronenhamias** [comment]
meanwhile you can are invited to the gitter channel and ask questions it might be useful
https://gitter.im/scalecube/Lobby
