### ISSUE TITLE
Website expired?

### ISSUE THREAD

**Issue by vinjana** [scalecube/scalecube-services#804]
The services.html, etc. pages, linked from the readme file is reported to be expired by the hoster. Fortunately, I got the idea to search a copy in the WaybackMachine/Internet Archive (there is one from January 2020). 

Even if you don't write new docs, maybe the old documenation still is helpful and could be moved to the Github wiki, or so.

**Comment by ronenhamias** [comment]
website moved here:

http://scalecube.github.io/

fixed links in readme

thanks!

**Comment by vinjana** [comment]
Thank you!
