### ISSUE TITLE
Add AutoCloseable on Microservices

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#830]
Subj.

**Comment by aharonha** [comment]
Did you mean [Cleaner](https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html)?

**Comment by artem-v** [comment]
> Did you mean [Cleaner](https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html)?

Hey, hey! Hi @aharonha.  No, not a cleaner, just a simple AutoClosable in order to use `Microservices`  in try-with-resources blocks.

**Comment by aharonha** [comment]
Legit 👍
